name: PaperBackup
version: 1.0
main: ua.vlad.backup.PaperBackup
api-version: '1.21'
author: Vlad
description: A plugin to stream zip backups of your Paper server to Google Drive.
commands:
  backup:
    description: Control backup system.
    permission: backup.admin
    usage: /<command> [run|status|reload]
permissions:
  backup.admin:
    description: Allows administration of server backups.
    default: op
